services:
  bot:
    build: .
    container_name: python-bot
    volumes:
      - .:/app
    depends_on:
      - db-bot

  # db-bot:
  #   image: postgres:latest
  #   container_name: postgres-bot
  #   environment:
  #     POSTGRES_USER: POSTGRES_USER
  #     POSTGRES_PASSWORD: POSTGRES_PASSWORD
  #     POSTGRES_DB: POSTGRES_DB
  #   ports:
  #     - ${POSTGRES_PORT}:5432