services:
    bot:
        image: bot
        container_name: bot
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/potiserpent
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 5
